export const login_user = (payload)=>({'type':'LOGIN', payload:payload})
export const addProduct = (payload)=>({'type':'ADD_PRODUCT', payload:payload})
export const filterBYPrice = ()=>({'type':'FILTER_BY_PRICE'})
export const filterBYQty = ()=>({'type':'FILTER_BY_Qty'})
export const logout = ()=>({'type':'LOGOUT'})